#!/usr/bin/env ruby

# Copyright (c) 2017 Minqi Pan <pmq2001@gmail.com>
# 
# This file is part of Node.js Compiler, distributed under the MIT License
# For full terms see the included LICENSE file

require 'shellwords'
require 'fileutils'

puts `git clone --depth 1 https://github.com/cnpm/cnpmjs.org`
raise 'git failed' unless $?.success?
Dir.chdir('cnpmjs.org')

outpath = File.expand_path((Gem.win_platform? ? 'a.exe' : 'a.out'), Dir.pwd)
FileUtils.rm_f(outpath)

pid = spawn("ruby ../bin/nodec dispatch.js")
pid, status = Process.wait2(pid)
raise "Failed running nodec for nodeclub" unless status.success?

raise unless File.exist?(outpath)
raise unless File.size(outpath) >= 10_000_000

if Gem.win_platform?
  outpath = %Q{"#{outpath}"}
else
  File.chmod(0777, outpath)
  outpath = Shellwords.escape(outpath)
end
