#!/usr/bin/env ruby

# Copyright (c) 2016-2017 Minqi Pan <pmq2001@gmail.com>
# 
# This file is part of Node.js Compiler, distributed under the MIT License
# For full terms see the included LICENSE file

puts `git clone --depth 1 https://github.com/jashkenas/coffeescript.git`
raise 'git failed' unless $?.success?
Dir.chdir('coffeescript')
pid = spawn('ruby ../bin/nodec -o coffee bin/coffee')
pid, status = Process.wait2(pid)
raise "Failed running nodec bin/coffee" unless status.success?

raise unless File.exist?('coffee')
raise unless File.size('coffee') >= 1_000_000
File.chmod(0777, 'coffee')
expect(`coffee --help`).to include %q{If called without options, `coffee` will run your script.}
expect(`coffee --eval "console.log(((x) -> x * x)(8))"`.to_i).to be 64
