#!/usr/bin/env ruby

# Copyright (c) 2016-2017 Minqi Pan <pmq2001@gmail.com>
# 
# This file is part of Node.js Compiler, distributed under the MIT License
# For full terms see the included LICENSE file

require 'shellwords'
require 'fileutils'

puts `git clone --depth 1 https://github.com/jashkenas/coffeescript.git`
raise 'git failed' unless $?.success?
Dir.chdir('coffeescript')

outpath = File.expand_path((Gem.win_platform? ? 'a.exe' : 'a.out'), Dir.pwd)
FileUtils.rm_f(outpath)

pid = spawn("ruby ../bin/nodec bin/coffee")
pid, status = Process.wait2(pid)
raise "Failed running nodec for coffeescript" unless status.success?

raise unless File.exist?(outpath)
raise unless File.size(outpath) >= 10_000_000

if Gem.win_platform?
  outpath = %Q{"#{outpath}"}
else
  File.chmod(0777, outpath)
  outpath = Shellwords.escape(outpath)
end

raise unless `#{outpath} --help`.include?(%q{If called without options, `coffee` will run your script.})
raise unless $?.success?
raise unless 64 == `#{outpath} --eval "console.log(((x) -> x * x)(8))"`.to_i
raise unless $?.success?
