#!/usr/bin/env ruby

# Copyright (c) 2016-2017 Minqi Pan <pmq2001@gmail.com>
# 
# This file is part of Node.js Compiler, distributed under the MIT License
# For full terms see the included LICENSE file

puts `git clone --depth 1 https://github.com/cnodejs/nodeclub.git`
raise 'git failed' unless $?.success?
Dir.chdir('nodeclub')
pid = spawn('ruby ../bin/nodec app.js')
pid, status = Process.wait2(pid)
raise "Failed running nodec app.js" unless status.success?
