#!/usr/bin/env ruby

require "enclose/io/compiler"

module Enclose
  module IO

    usage = %Q{

enclose-io-compiler v#{Compiler::VERSION}

Usage:
  enclose-io-compiler [node_version] [module_name] [module_version]

    }.strip

    unless 4 == ARGV.size
      puts usage
      exit 1
    end

    begin
      instance = Compiler.new *ARGV
      instance.npm_install
      instance.inject_entrance
      instance.compile
      instance.die
    rescue Compiler::Error => e
      STDERR.puts e.message
      exit 2
    end

  end
end
