#!/usr/bin/env ruby

require "enclose/io/compiler"

module Enclose
  module IO

    usage = %Q{

enclose-io-compiler v#{Compiler::VERSION}

Usage:
  enclose-io-compiler [node_version] [module_name] [module_version] [bin_name] [output_path]

E.g.:
  enclose-io-compiler node-v6.8.0 coffee-script 1.11.1 coffee /tmp/coffee-1.11.1-node-v6.8.0-darwin-x64

Available Node.js versions:
  #{Compiler.node_versions.join(', ')}

    }.strip

    unless 5 == ARGV.size
      puts usage
      exit 1
    end

    begin
      instance = Compiler.new ARGV
      instance.run!
      instance.clean_work_dir unless ENV['ENCLOSE_IO_KEEP_WORK_DIR']
    rescue Compiler::Error => e
      STDERR.puts e.message
      exit 2
    end

  end
end
