#!/usr/bin/env ruby

# Copyright (c) 2016-2017 Minqi Pan
# 
# This file is part of Node.js Compiler, distributed under the MIT License
# For full terms see the included LICENSE file

require "node/compiler"
require 'optparse'

USAGE = %Q{

Node.js Compiler (nodec) v#{::Node::Compiler::VERSION} (runtime #{::Node::Compiler.node_version})
Compiler for Node.js which compiles your project into a single executable.

Usage: nodec [OPTION]... [ENTRANCE]

}.strip

EXAMPLES = %Q{

Example 1: Compiling a CLI project
    git clone https://github.com/jashkenas/coffeescript.git
    cd coffeescript
    nodec bin/coffee

Example 2: Compiling a web application
    git clone https://github.com/cnodejs/nodeclub.git
    cd nodeclub
    cp config.default.js config.js
    nodec app.js

Example 3: Compiling a npm package
    nodec --npm-package=coffee-script coffee

Bug reports and pull requests are welcome on GitHub at
https://github.com/pmq20/node-compiler

}.strip

options = {}

outer_opts = nil

usage = lambda do |out|
  out.puts outer_opts
  out.puts
  out.puts EXAMPLES
end

OptionParser.new do |opts|
  opts.banner = USAGE

  opts.on("-pDIR", "--project-root=DIR", "Speicifies the path to the root of the project") do |dir|
    options[:project_root] = dir
  end

  opts.on("-oFILE", "--output=FILE", "Speicifies the path of the output file") do |file|
    options[:output] = file
  end

  opts.on("-dDIR", "--tmpdir=DIR", "Speicifies the directory for temporary files") do |dir|
    options[:tmpdir] = dir
  end

  opts.on("--make-args=ARGS", "Passes extra arguments to make") do |args|
    options[:make_args] = args
  end

  opts.on("--vcbuild-args=ARGS", "Passes extra arguments to vcbuild.bat") do |args|
    options[:vcbuild_args] = args
  end

  opts.on("--npm-package=NAME", "Compiles the specified npm package") do |name|
    options[:npm_package] = name
  end

  opts.on("--npm-package-version=VER", "Compiles the specified version of the npm package") do |ver|
    options[:npm_package_version] = ver
  end

  opts.on("-v", "--version", "Prints the version of nodec and exit") do
    puts ::Node::Compiler::VERSION
    exit 0
  end

  opts.on("--node-version", "Prints the version of the Node.js runtime and exit") do
    puts ::Node::Compiler.node_version
    exit 0
  end

  opts.on("-h", "--help", "Prints this help and exit") do
    usage.call(STDOUT)
    exit 0
  end

  outer_opts = opts
end.parse!

entrance = ARGV[-1]
unless entrance.kind_of?(String) && entrance.length > 0
  usage.call(STDERR)
  exit 1
end

begin
  instance = ::Node::Compiler.new entrance, options
  instance.run!
rescue ::Node::Compiler::Error => e
  STDERR.puts e.message
  exit 1
end
